var str1 = "ppqq";
var str2 = "aaaa";
document.writeln(str1);
console.log(str1.charAt(3));
console.log(str1.concat(str2));
console.log(str1);
var str3 = str1 + str2;
document.writeln("<br>" + str3);
document.writeln(str3.charAt(3));
console.log(str3.indexOf("a"));
var str4 = "  123wwwwwaaaa__oooaa    ";
console.log(str4);
str4.trim();
console.log(str4);
console.log(str4.trim());